version: 0.2

phases:
  pre_build:
    commands:
      - sudo wget https://dev.mysql.com/get/mysql80-community-release-el9-4.noarch.rpm
      - sudo yum localinstall mysql80-community-release-el9-4.noarch.rpm -y
      - sudo yum install mysql-server -y
      - sudo dnf install docker -y
  build:
    commands:
        - npm install
        - npm audit fix --force
        - echo "Building docker image"
        - cat ./my_password.txt | docker login --username nithishns --password-stdin
        - docker build . -t docker.io/nithishns/test:v1   
        - docker push docker.io/nithishns/test:v1 
        - echo "Build success!!!!!"
  post_build:
    commands:
        - docker run -d -p 3002:3000 --name node1 docker.io/nithishns/test:v1 
        - npm start
        - echo "Post Build success!!!!!"
