version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
        - echo "Building docker image"
        - cat ./my_password.txt | docker login --username nithishns --password-stdin
        - docker build . -t docker.io/nithishns/test:v1   
        - docker push docker.io/nithishns/test:v1 
        - echo "Build success!!!!!"
    artifacts:
      files:
        - '*/'

